# Generated by Django 5.2.12 on 2026-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='host',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='mitre_technique',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
