# Generated by Django 5.2.12 on 2026-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_host_incident_mitre_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10),
        ),
    ]
